[pytest]
# Включаем вывод логов в консоль (CLI)
log_cli = true
# Устанавливаем уровень логирования (INFO и выше)
log_cli_level = INFO
# Настраиваем формат: Время [Уровень] Сообщение
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format=%H:%M:%S